# Generated by Django 5.2.4 on 2025-08-13 10:22

import MAIN_APP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MAIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='C_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='college-photo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('map_link', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('syllabus', models.FileField(upload_to='syllabus/')),
                ('details', models.TextField(blank=True, null=True)),
                ('course_desc', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(help_text='Enter folder name (e.g. nature, prices, etc.)', max_length=100)),
                ('events_photo', models.ImageField(upload_to=MAIN_APP.models.event_upload_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='facility/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_content', models.CharField(max_length=200)),
                ('links', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='imp_person/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('post', models.CharField(max_length=100)),
                ('sec_post', models.CharField(blank=True, max_length=300, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('review_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enroll', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('student_mobile', models.CharField(max_length=15, unique=True)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField(blank=True, null=True)),
                ('admission_year', models.PositiveIntegerField()),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('EC', 'IC'), ('IC', 'IC')], max_length=50)),
                ('mode_of_admission', models.CharField(choices=[('Direct', 'Direct'), ('Entrance Exam', 'Entrance Exam')], max_length=50)),
                ('admission_type', models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral')], max_length=50)),
                ('tenth_school', models.CharField(max_length=100)),
                ('tenth_board', models.CharField(max_length=50)),
                ('tenth_passing_year', models.PositiveIntegerField()),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ITI_or_Twelfth', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('aadhaar_card', models.FileField(upload_to='students/docs/aadhaar/')),
                ('caste_certificate', models.FileField(blank=True, null=True, upload_to='students/docs/caste_certificate/')),
                ('domicile_certificate', models.FileField(blank=True, null=True, upload_to='students/docs/domicile_certificate/')),
                ('transfer_certificate', models.FileField(upload_to='students/docs/transfer_certificate/')),
                ('character_certificate', models.FileField(upload_to='students/docs/character_certificate/')),
                ('marksheets', models.FileField(upload_to='students/docs/marksheets/')),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=200)),
                ('Qualification', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='teacher/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('book_price', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stu_enroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MAIN_APP.student')),
            ],
        ),
        migrations.CreateModel(
            name='Corner_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=100)),
                ('content_desc', models.TextField(blank=True, null=True)),
                ('content_file', models.FileField(upload_to='stu_content/')),
                ('content_type', models.CharField(max_length=20)),
                ('to_branch', models.CharField(max_length=20)),
                ('to_year', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MAIN_APP.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='MAIN_APP.teacher')),
            ],
        ),
    ]
