# Generated by Django 5.2.4 on 2025-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corner_content',
            name='content_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='corner_content',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='stu_content/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EC', 'EC'), ('IC', 'IC')], max_length=50),
        ),
    ]
