# Generated by Django 5.2.4 on 2025-08-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0004_book_bookcopy_issue_delete_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_name',
        ),
    ]
