# Generated by Django 5.2.4 on 2025-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0005_rename_title_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.CharField(max_length=20),
        ),
    ]
