# Generated by Django 5.2.4 on 2025-08-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0006_alter_bookcopy_copy_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcopy',
            old_name='copy_number',
            new_name='book_set_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='copy',
            new_name='book_id',
        ),
    ]
