# Generated by Django 5.2.4 on 2025-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0007_rename_copy_number_bookcopy_book_set_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='book_id',
            new_name='book_set',
        ),
    ]
