# Generated by Django 5.2.4 on 2025-08-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0008_rename_book_id_issue_book_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(choices=[('Lecturer Computer', 'Lecturer Computer'), ('Lecturer Electronics', 'Lecturer Electronics'), ('Lecturer Instrumentation and Control', 'Lecturer Instrumentation and Control'), ('Lecturer (Applied Science and Humanities)', 'Lecturer (Applied Science and Humanities)'), ('Librarian', 'Librarian'), ('Workshop Instructor', 'Workshop Instructor')], max_length=200),
        ),
    ]
