# Generated by Django 5.2.4 on 2025-08-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0009_alter_teacher_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C_photo',
            new_name='college_photo',
        ),
    ]
