# Generated by Django 5.2.4 on 2025-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0010_rename_c_photo_college_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='addmission_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(blank=True, default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus/'),
        ),
    ]
