# Generated by Django 5.2.4 on 2025-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0011_course_addmission_process_course_group_course_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='group',
            new_name='Duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='addmission_process',
        ),
        migrations.AddField(
            model_name='course',
            name='Eligibility',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
