# Generated by Django 5.2.5 on 2025-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_APP', '0012_rename_group_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='Eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
